moddio/moddio2

src/gameClasses/Unit.js

2418 - Cannot read properties of undefined
[Uncaught TypeError]
`errorLog`
Legacy with no client physics engine does not have script component

fix for rollbar BE #2418

---

src/gameClasses/Unit.js

refactor to fix bypass of return statement

---

src/client.js

rollbar errors #0872, #0887, #0870, #0871, #3373 and others

fix for menuUi undefined when calling clipImageForShop/scaleFactor

---

src/client.js

copy fix from #360 to apply change to legacy games

---

engine/components/physics/box2d/Box2dComponent.js
src/gameClasses/components/script/VariableComponent.js

reserve triggering item/projectile for the touching entity.
issue found by @Billyboyyy

Trigger fix

---

engine/components/TaroInputComponent.js

Getting rid of old _chatHandler function and moving it into editor repo

removed ChatHandler

---

engine/core/TaroEntity.js
src/gameClasses/Unit.js
src/gameClasses/components/script/ActionComponent.js

the units' facing angles weren't updated on client side until the unit moved

Some fixes

---

src/gameClasses/Item.js
src/gameClasses/components/unit/AttributeComponent.js

add fix from PR#404 to legacy

---

src/gameClasses/components/MapComponent.js
src/gameClasses/components/unit/AIComponent.js

Added A* algorithm for AI
- The algorithm will work for fight, move. Flee will keep simple
- The algorithm works based on grid
Video
https://github.com/moddio/taro2/assets/62375288/2c361d19-ffda-4fc8-a701-eed2be3a2a40

A* algorithm for AI units

---

src/gameClasses/DeveloperMode.js
src/gameClasses/components/script/ActionComponent.js
ts/src/gameClasses/DeveloperMode.ts

Added Edit Map Tile Action to ActionComponent.js.

Edit Map Tile Action

---

src/gameClasses/components/script/ActionComponent.js
src/gameClasses/components/script/VariableComponent.js

added loadMapFromString Action to ActionComponent.js and added getMapJson to VariableComponent.js.

Load Map From String Action and getMapJson variable

---

src/gameClasses/ClientNetworkEvents.js

https://trello.com/c/LGoWjfrI/8802-devlog-streaming-from-server-to-client

Log errors to new reporting tab

---

engine/components/physics/box2d/Box2dComponent.js

sorry, my bad, just copy step twice

fix: remove excess step

---

src/gameClasses/components/unit/AIComponent.js

https://github.com/moddio/taro2/assets/62375288/e3ad116c-5481-47de-83b1-14a7a2ad82a2
They will now directly walk to the target position, if no wall blocked
(based on https://github.com/moddio/taro2/pull/439 code)
JSON: 
[game.txt](https://github.com/moddio/taro2/files/12035850/game.txt)

A* no blocking if go straight

---

engine/core/TaroEntity.js
src/gameClasses/Projectile.js

Revert "let custom w/h from action dictate projectile size"

---

src/client.js

- phaser will try to use taro.scaleMapDetails, but before physicsLoaded, it's undefined, so new promise to wait for it

fix: taro.scaleMapDetails is undefined when box2dwasm is still in init

---

src/gameClasses/Unit.js
src/gameClasses/components/script/VariableComponent.js

adds support for variables:
`allUnitsOfType`
`allItemsOfType`
`allProjectilesOfType`

Variable group by type

---

src/gameClasses/components/unit/AbilityComponent.js
src/gameClasses/components/unit/AttributeComponent.js

Attribute trigger fixes

---

src/gameClasses/components/script/ActionComponent.js

Stops moving the unit in the X and Y axis

Add stopMovingUnit

---

src/gameClasses/components/script/VariableComponent.js

Returns the upper case of the provided input

Add toUpperCase

---

src/gameClasses/components/script/VariableComponent.js

Add ceiling function

---

src/gameClasses/components/script/ActionComponent.js

Purpose for this action:
1. Looping every key in the object
2. Looping every index in the string and array
Notes:
1. Only (number - string), (string - object) is allowed.
2. When you loop the index of a string, the index starts at 0. (Perhaps I should set it to 1?)

"For in" loop action

---

src/gameClasses/components/script/ActionComponent.js
src/gameClasses/components/script/VariableComponent.js

Copy of last PR as the last PR for some reason had conflicts, this should not

Add resetPlayerName function and getPlayerUsername variable

---

engine/components/network/net.io/TaroNetIoServer.js
engine/components/network/net.io/net.io-server/index.js
server/ServerNetworkEvents.js
src/gameClasses/components/GameComponent.js
src/gameClasses/components/script/VariableComponent.js
ts/types/EntityStats.d.ts

Adds checks for whether a player is on mobile when they join, isMobile boolean on players, and isPlayerOnMobile.

Add mobile detection, isPlayerOnMobile function

---

src/gameClasses/ClientNetworkEvents.js
src/gameClasses/components/script/ActionComponent.js

Revert "Filter 3"

---

src/gameClasses/ClientNetworkEvents.js
src/gameClasses/components/script/ActionComponent.js

This reverts commit 20144f7e57d891fd5ea4addac734361352007b83, reversing changes made to 979a92def77c8d02716664107b15b167f0212f5c.

Revert "Merge pull request #746 from bruh-9000/filter"

---

src/gameClasses/components/script/ActionComponent.js
src/gameClasses/components/script/ParameterComponent.js
src/gameClasses/components/script/ScriptComponent.js

- add comments for error report
- rename actionBlockIdx to actionLineNumber

Chore add comments and rename parameter for error report

---

ts/src/renderer/three/ThreeCamera.ts
ts/src/renderer/three/ThreeRenderer.ts
ts/src/renderer/three/ThreeSprite.ts

This PR adds billboard sprites to the three.js renderer.

Billboards

---

ts/src/renderer/phaser/classes/PhaserAnimatedEntity.ts

- fix: animation won't be restored to the default anim
[restore_to_default_anim.txt](https://github.com/moddio/moddio2/files/14328328/restore_to_default_anim.txt)

fix: animation won't be restored to the default anim

---

engine/components/network/TaroStreamComponent.js
engine/core/TaroEntity.js
src/gameClasses/components/script/ParameterComponent.js
ts/src/renderer/phaser/classes/PhaserProjectile.ts
ts/types/TaroEntity.d.ts

fix: notValue is undefined

---

ts/src/renderer/phaser/classes/PhaserAnimatedEntity.ts

- fix: default animation loop inf when it's loop 1
[[Just Testing Case] animation_2024220_620.json](https://github.com/moddio/moddio2/files/14337380/Just.Testing.Case.animation_2024220_620.json)

fix: default animation loop inf when it's loop 1

---

ts/src/renderer/phaser/classes/devmode/TileEditor.ts
ts/types/TaroEngine.d.ts

- add undo/redo to clear layer

Feat add undo/redo to clear layer

---

ts/src/renderer/three/ThreeCamera.ts

This PR fixes the issue of mouse input not working when a game is started with perspective camera.

Fix mouse input not working when perspective camera

---

ts/src/renderer/three/ThreeAttributeBar.ts
ts/src/renderer/three/ThreeCamera.ts
ts/src/renderer/three/ThreeChatBubble.ts
ts/src/renderer/three/ThreeLabel.ts
ts/src/renderer/three/ThreeRenderer.ts

This PR changes how zoom works by changing the camera distance instead of using orthographic zoom. Now zoom also works for the perspective camera.

Set camera zoom by changing camera distance

---

ts/src/renderer/three/ThreeCamera.ts
ts/src/renderer/three/ThreeRenderer.ts
ts/src/renderer/three/ThreeSprite.ts

This PR fixes the zoom direction that was going in the wrong direction in #825 and billboard sprites still not working correctly in #824.

Hotfix zoom direction and billboard sprites

---

ts/src/renderer/three/ThreeCamera.ts

This PR fixes billboard sprites not facing camera, third attempt :')

Fix billboard not facing camera

---

src/gameClasses/components/script/ActionComponent.js

- add comments to the getNestedActionsLength in ActionComponent
- fix the obj.else maybe is undefined

fix: add comments and the else maybe undefined

---

engine/core/TaroEntity.js
src/gameClasses/components/entity/AttributeComponent.js

...when source of update call is loadPersistentData

silence attribute related triggers... 

---

pnpm-lock.yaml
ts/src/renderer/phaser/classes/devmode/TileEditor.ts
ts/src/renderer/phaser/scenes/GameScene.ts

When you edit tiles using the edit tile action, users who join afterwards will not see the tiles updated but the original tile
any game.json, just edit the tile using anyway

fix: updated tiles not showing

---

src/gameClasses/components/script/ActionComponent.js

Purpose for this: for adding numbers inside the object through the action.
Reason for making this: For making the script not so complicated. Like you don't have to add numbers as a string inside an object then take out using string and then convert it to number.
(This is my first time making this stuff, so I am still not familiar with how it works.)

addNumberElement (Add (Number) element into object) Action

---

ts/src/renderer/three/ThreeFloatingText.ts
ts/src/renderer/three/ThreeLabel.ts
ts/src/renderer/three/ThreeParticleSystem.ts
ts/src/renderer/three/ThreeRenderer.ts
ts/src/renderer/three/ThreeSprite.ts
ts/src/renderer/three/utils.ts
ts/types/Particle.d.ts

This PR improves the rendering order of entities.

Improve 3D renderer rendering order of entities

---

ts/src/renderer/three/ThreeRenderer.ts
ts/types/GameComponent.d.ts

This PR hooks up the default camera pitch setting to the renderer.

Integrate default camera pitch setting

---

ts/src/renderer/three/ThreeCamera.ts

This PR:
- Displays the zoom level in de camera debug UI when "/" is pressed.
- Add min/max zoom levels for the orthographic camera
- Fix the orthographic camera not resizing properly

Improve the 3D renderer camera zoom functionality

---

ts/src/renderer/three/ThreeCamera.ts
ts/src/renderer/three/ThreeRenderer.ts

This PR fixes the bug of the sound effects not moving with the player.

Fix sounds not moving with the player in the 3D renderer

---

src/gameClasses/components/ShopComponent.js

- Updated Item and Skin Shop UI

Updated shop colors

---

src/client.js
ts/src/renderer/three/Renderer.ts

This PR allows the background color of the scene to be set by the game config file.

Allow the 3D renderer background color to be set

---

ts/src/renderer/three/Camera.ts
ts/src/renderer/three/Sprite.ts

This PR auto calcs the sprite z-offset.

Auto calc the sprite z-offset so it stays on the 'floor' in the 3D renderer.

---

ts/src/renderer/phaser/classes/PhaserAnimatedEntity.ts
ts/src/renderer/three/Renderer.ts
ts/types/GameComponent.d.ts

for now the items in three renderer which with same cellsheet will overwrite each other's frames

fix: items with same cellsheet will overwrite each other

---

ts/src/renderer/three/Renderer.ts
ts/src/renderer/three/TextureRepository.ts

This PR fixes map rendering issues caused by the initialization code being triggered multiple times.

Fix 3D renderer map rendering bug caused by initialization code being triggered multiple times

---

src/gameClasses/components/ControlComponent.js
src/gameClasses/components/unit/AbilityComponent.js

This PR makes the WASD and AD movement more responsive. Now when you press left -> left and right -> left you keep moving left instead of stopping and forcing you to re-press the left key to move left again.

Make movement more responsive

---

engine/components/physics/box2d/Box2dComponent.js
engine/core/TaroClass.js
server/server.js
ts/engine/components/physics/box2d/dists.ts
ts/engine/components/physics/box2d/distsWrapper/box2dwasmWrapper.ts

- fix: replace setInterval with callback for await box2dwasm.init()

fix: replace setInterval with callback for await box2dwasm.init()

---

engine/components/network/net.io/net.io-server/index.js
src/client.js

[Why is this needed? What does it help accomplish?](feat: add callback to the client physcisComponent)

feat: add callback to the client physcisComponent

---

engine/core/TaroEntity.js
src/gameClasses/components/entity/AttributeComponent.js

when loading persistent attribute data on server

force stream of max min that were ignored

---

engine/components/TaroInputComponent.js
src/gameClasses/components/ControlComponent.js

This PR makes it so that all keyboard keys and mouse buttons are released when the browser tab is inactive.

Release user input when browser tab is inactive

---

ts/src/renderer/three/FloatingText.ts
ts/src/renderer/three/Particles.ts
ts/src/renderer/three/Renderer.ts

This PR spawns floating text on the floor (first layer) or at the height of the unit the camera is currently following. It also fixes a bug where particle emitters didn't despawn.

Spawn floating text on the floor or camera follow target's height

---

src/gameClasses/components/ShopComponent.js

Skin shop UI update

---

engine/components/network/net.io/TaroNetIoClient.js
engine/components/network/net.io/TaroNetIoServer.js
engine/components/network/net.io/net.io-client/index.js
server/ServerNetworkEvents.js
server/server.js
src/gameClasses/ClientNetworkEvents.js
src/gameClasses/Unit.js

fix: server responds to ping immediately, track latency on newrelic

---

src/gameClasses/ClientNetworkEvents.js
src/gameClasses/Unit.js

fix: send ping as soon as pong received from server

---

engine/components/network/net.io/net.io-client/index.js

fix latency tracking

---

src/gameClasses/components/script/ActionComponent.js

Preview
https://github.com/moddio/taro2/assets/62375288/df46711c-1144-416c-a7e7-c5399577c5b2

Added action applyImpulseOnEntityAngle

---

src/gameClasses/components/script/ParameterComponent.js

https://github.com/moddio/moddio2/pull/460/files

Add 'playerAttributeRegen' and 'entityAttributeRegen'

---

engine/components/network/net.io/net.io-client/index.js
src/gameClasses/ClientNetworkEvents.js

Ping updates

---

src/gameClasses/components/script/ParameterComponent.js

https://github.com/moddio/moddio2/pull/512/files

getPositionInFrontOfPosition fix

---

server/ServerNetworkEvents.js

If there are multiple users with the same name, scripts that utilize player names may confuse them to be the same player and have issues. Rare, but possible, I've seen multiple users with the same name before.
[Link](https://github.com/moddio/moddio2/pull/773)

Fix duplicate user name bug

---

server/server.js
src/ClientConfig.js
src/client.js
src/gameClasses/ClientNetworkEvents.js
src/gameClasses/components/script/ActionComponent.js
ts/src/renderer/three/DynamicFloatingText.ts
ts/src/renderer/three/Label.ts
ts/src/renderer/three/Renderer.ts

Add dynamic floating text to the 3D renderer. Responds to the new createDynamicFloatingText script action.

3D: Add dynamic floating text

---

engine/core/TaroEntity.js
src/client.js
src/gameClasses/ClientNetworkEvents.js
src/gameClasses/Item.js
src/gameClasses/Projectile.js
src/gameClasses/Unit.js
src/gameClasses/components/script/ActionComponent.js
ts/src/renderer/phaser/classes/PhaserAnimatedEntity.ts
ts/src/renderer/phaser/classes/PhaserParticle.ts
ts/src/renderer/phaser/scenes/GameScene.ts
ts/src/renderer/three/Particles.ts
ts/src/renderer/three/Renderer.ts

Remove old particle system. Add new particle system.

add new system for particles; start/stop actions, rendering

---

package-lock.json
package.json
src/gameClasses/components/MobileControlsComponent.js
ts/src/renderer/phaser/scenes/MobileControlsScene.ts

Implements HTML joysticks for player movements in mobile

adding html joysticks

---

ts/src/renderer/phaser/classes/PhaserJoystick.ts
ts/src/renderer/phaser/scenes/MobileControlsScene.ts

disabled show for phaser joystick

---

src/gameClasses/components/MobileControlsComponent.js

enable dynamic html joysticks

---

server/ServerNetworkEvents.js
src/gameClasses/Item.js
src/gameClasses/Player.js
src/gameClasses/Unit.js
src/gameClasses/components/ControlComponent.js
src/gameClasses/components/MobileControlsComponent.js
src/gameClasses/components/unit/AIComponent.js
src/gameClasses/components/unit/AbilityComponent.js
ts/src/gameClasses/EntitiesToRender.ts
ts/src/renderer/three/Camera.ts
ts/src/renderer/three/Renderer.ts
ts/src/renderer/three/Sprite.ts
ts/types/ControlComponent.d.ts

This PR implements a relative control scheme. No matter what angle the camera is facing, moving left always moves the character to the left of the screen.

3D: Add relative movement control scheme

---

src/gameClasses/Player.js
src/gameClasses/components/MobileControlsComponent.js

added html buttons

---

ts/src/renderer/three/Renderer.ts

fixing joysticks movement issue in 3d games

---

src/gameClasses/components/MobileControlsComponent.js

- fixes position of html buttons

fixed html button position

---

src/gameClasses/components/MobileControlsComponent.js

- fixed look and fire joystick issues

Joystick fix

---

src/gameClasses/ClientNetworkEvents.js
src/gameClasses/components/script/ActionComponent.js

movePlayerToMap action updates

---

server/server.js
src/client.js
src/gameClasses/ClientNetworkEvents.js
src/gameClasses/components/script/ActionComponent.js

action: send player to last spawning map

---

ts/src/renderer/three/Voxels.ts

after impl brush and earser, the new tiles won't update the neighbors' hidden faces
any game using threejs renderer

fix: hidden faces works not as expect

---

ts/src/renderer/three/Renderer.ts
ts/src/renderer/three/VoxelEditor.ts
ts/src/renderer/three/Voxels.ts

feat: make saving map work and tileId starts from 1 

---

ts/src/renderer/three/Renderer.ts
ts/src/renderer/three/VoxelEditor.ts
ts/src/renderer/three/VoxelMarker.ts
ts/src/renderer/three/Voxels.ts

feat: add the preview and fixed many issues

---

ts/src/renderer/three/Camera.ts

3D: Remap map controls

---

ts/src/renderer/three/Renderer.ts
ts/src/renderer/three/VoxelEditor.ts
ts/src/renderer/three/VoxelMarker.ts
ts/src/renderer/three/Voxels.ts
ts/types/TaroEngine.d.ts

fix: cycling data sending issue and impl undo/redo for editTile in threejs

---

src/gameClasses/Unit.js

Revert "call `Unit.updateNameLabel()` in all cases on client"

---

engine/core/TaroEngine.js
ts/src/renderer/three/Renderer.ts
ts/src/renderer/three/VoxelEditor.ts
ts/src/renderer/three/VoxelMarker.ts

feat: add drag to draw

---

ts/src/renderer/three/VoxelMarker.ts

fix: eraser blink

---

ts/src/renderer/three/Sprite.ts
ts/src/renderer/three/VoxelEditor.ts
ts/src/renderer/three/Voxels.ts
ts/src/renderer/three/entities/Region.ts

At the cost of no transparent map tiles, for now.

3D: Improve render order of transparent objects

---

ts/src/gameClasses/DeveloperMode.ts
ts/src/renderer/three/Renderer.ts
ts/src/renderer/three/VoxelEditor.ts
ts/src/renderer/three/VoxelMarker.ts
ts/src/renderer/three/Voxels.ts

feat: add fill tool, hide/show layer and clear layer, all impl the undo/redo

---

src/gameClasses/components/ShopComponent.js

fixed image resize issues with skin shop

---

src/gameClasses/components/script/ActionComponent.js

temper prevention fixes

---

src/gameClasses/Item.js
src/gameClasses/Projectile.js
src/gameClasses/Unit.js

force hide unit on creation race-con; only update item body from `Unit.show()` if required

fixes for niche unit and item `show`/`hide`

---

src/gameClasses/components/script/ActionComponent.js

refactoring

---

src/gameClasses/components/ui/MenuUiComponent.js

remove auto reconnect timer

---

src/gameClasses/components/MobileControlsComponent.js

fixed joystick code

---

src/gameClasses/components/MobileControlsComponent.js

fixed bug where ability buttons where loaded on mobile

---

src/gameClasses/components/script/ActionComponent.js
src/gameClasses/components/script/ParameterComponent.js

feat: add getLastProgressCompletedQuestId and getLastCompletedQuestId, fix the crash error of isQuestOngoing and so on

---

ts/src/renderer/three/EntityEditor.ts
ts/src/renderer/three/EntityGizmo.ts
ts/src/renderer/three/EntityManager.ts
ts/src/renderer/three/InitEntity.ts
ts/src/renderer/three/Model.ts

- fixed 'delete' entity
- fixed scaling entity in 'map' tab

Editor 3d bugfixes

---

engine/core/TaroEntity.js
server/ServerConfig.js
src/ClientConfig.js
src/gameClasses/Player.js
src/gameClasses/components/quest/QuestComponent.js
src/gameClasses/components/script/ActionComponent.js
src/gameClasses/components/script/ParameterComponent.js

- to store and load the quests data and prevent developers to update other devleopers' quests

feat: add QuestComponent

---

engine/core/TaroEntity.js
src/gameClasses/components/script/ActionComponent.js

fix: complete first then trigger the event

---

src/gameClasses/components/script/ActionComponent.js
src/gameClasses/components/script/ParameterComponent.js

to let developers can handle their questProgressUpdated in single common script

feat: add getLastProgressUpdatedQuestId parameter and questProgressUpdated trigger

---

src/gameClasses/components/script/ActionComponent.js

added temper prevention for entity update actions and reporting updates

---

server/ServerNetworkEvents.js

playerPurchasesItem return itemTypeId now, which is wrong, should return itemId instead

fix: playerPurchasesItem should return itemId not itemTypeId

---

src/gameClasses/components/script/ActionComponent.js
src/gameClasses/components/script/ParameterComponent.js

feat: unified the questId parameter function and add two more actions for it

---

engine/components/network/net.io/net.io-server/index.js
src/gameClasses/Player.js
src/gameClasses/components/GameComponent.js
src/gameClasses/components/script/ActionComponent.js

user data saving support for guest users

---

engine/components/network/net.io/net.io-server/index.js
src/gameClasses/Player.js
src/gameClasses/components/GameComponent.js
src/gameClasses/components/script/ActionComponent.js

Revert "user data saving support for guest users"

---

src/gameClasses/components/script/ActionComponent.js

feat: add the missing triggeredBy

---

ts/src/gameClasses/EntitiesToRender.ts

This update fixes item anchor when using Phaser renderer. Doesn't affect any other feature, nor interfere with the 3d renderer

Fixed item anchor with Phaser renderer

---

engine/components/network/net.io/net.io-server/index.js
server/server.js

guest user data save - update to guest user token

---

engine/core/TaroEntity.js

fix: init of the quests

---

src/gameClasses/components/quest/QuestComponent.js

fix: stream first then remove the quest

---

engine/core/TaroEntity.js

fix: update the clients' completed quests data

---

engine/components/network/net.io/net.io-server/index.js

prevent player joins if server is not accepting players

---

ts/src/renderer/three/EntityGizmo.ts
ts/src/renderer/three/InitEntity.ts

feat: support undo/redo for gizmo

---

engine/loader.js
src/gameClasses/Player.js
src/gameClasses/components/ShopComponent.js
src/gameClasses/components/ui/MenuUiComponent.js
src/gameClasses/components/ui/ScoreboardComponent.js

change root url for all api calls to support static exports

---

src/client.js
src/gameClasses/ClientNetworkEvents.js
src/gameClasses/components/script/ActionComponent.js

map transition support for static export

---

engine/core/TaroEntity.js
src/gameClasses/Item.js
src/gameClasses/Unit.js

Revert "fix for item tweens"

---

src/gameClasses/Item.js
src/gameClasses/Unit.js

Revert "added client side support for item pick up/drop triggers"

---

ts/src/renderer/three/EntityEditor.ts
ts/src/renderer/three/EntityGizmo.ts
ts/src/renderer/three/InitEntity.ts

fix: scale transform for the 3d model gizmo

---

ts/src/renderer/three/EntityEditor.ts
ts/src/renderer/three/EntityGizmo.ts
ts/src/renderer/three/InitEntity.ts

fix: undo/redo for gizmo translation

---

src/client.js
ts/src/index.ts
ts/src/renderer/three/Renderer.ts

reset renderer fixes, reset after reinitializing taro

---

engine/components/network/net.io/net.io-client/index.js
engine/components/network/net.io/net.io-server/index.js

send guest user token as part of query

---

ts/src/renderer/three/entities/Item.ts
ts/src/renderer/three/entities/Unit.ts

I can't test loading skins locally, let's see if this fixes the issue of skins being loaded as pink squares.

Maybe fix loading skins

---

src/gameClasses/Item.js

Item was being displayed when moved from backpack to unselected inventory slot.

check if currentItemIndex matches index sent to `Item.changeItemIndex`

---

src/gameClasses/components/ui/ItemUiComponent.js

decreased drag co-effienct to 20

---

src/gameClasses/Item.js

Modify server-side position calculation of held Item. Fix Unit colliding with its own held Item.

use physics body position on server for Item's anchoredOffset calc

---

engine/components/physics/box2d/TaroEntityPhysics.js
src/gameClasses/Item.js
src/gameClasses/Unit.js

Revert "ensure that script action scaling of physics body is performed"

---

engine/components/physics/box2d/Box2dComponent.js
src/gameClasses/components/script/ActionComponent.js
ts/src/renderer/three/EntityEditor.ts
ts/src/renderer/three/InitEntity.ts
ts/src/renderer/three/Renderer.ts
ts/src/renderer/three/entities/Unit.ts

fix: rename update to updateAction for initEntities and add update to fix the billboard

---

src/client.js
ts/src/renderer/three/Renderer.ts

allow support of using existing canvas for threejs renderer

---

engine/core/TaroEntity.js
engine/core/TaroObject.js
ts/src/renderer/three/ParticleSystem.ts
ts/src/renderer/three/entities/Item.ts
ts/src/renderer/three/entities/Unit.ts

Revert "Support 3D rotation setting"

---

src/client.js
src/gameClasses/ClientNetworkEvents.js
src/gameClasses/Player.js
src/gameClasses/components/ui/MenuUiComponent.js

static export updates - integrate poki sdk

---

server/ServerNetworkEvents.js

save player data fixes

---

src/gameClasses/components/GameComponent.js

fix: only update the dev console when it's visible

---

engine/components/physics/box2d/Box2dComponent.js
engine/core/TaroEntity.js
ts/src/renderer/three/entities/Unit.ts

chore: rename depth for the model as temp_translation_y

---

ts/engine/components/physics/box2d/debugDrawWrapper/box2dwasmDebugDrawThree.ts
ts/engine/components/physics/box2d/distsWrapper/box2dwasmWrapper.ts

fix: disableDebug

---

ts/src/renderer/three/hud/FloatingText.ts

fix: floating text should not set matrixAutoUpdate as false, since they have lifespan and wont lasts so long, no need to handle it mannually

---

ts/engine/components/physics/box2d/distsWrapper/box2dwasmWrapper.ts

fix: do not create sensors for those entities without ai

---

ts/src/renderer/three/EntityManager.ts
ts/src/renderer/three/entities/Entity.ts
ts/src/renderer/three/entities/Item.ts
ts/src/renderer/three/entities/Unit.ts

fix: should updateMatrix after rotate and scale, also check the position.y

---

ts/engine/components/physics/box2d/distsWrapper/box2dwasmWrapper.ts

fix: the region should create sensor

---

engine/components/network/net.io/TaroNetIoServer.js
engine/components/network/net.io/net.io-client/index.js
server/ServerNetworkEvents.js

connection improvements for guests

---

src/gameClasses/components/ui/PlayerUiComponent.js

poki game sdk updates for in-game dialogues

---

ts/engine/components/physics/box2d/distsWrapper/box2dwasmWrapper.ts

fix: should not create sensors for none-ai entities

---

ts/src/renderer/three/hud/Attributes.ts
ts/src/renderer/three/hud/ChatBubble.ts
ts/src/renderer/three/hud/Element.ts
ts/src/renderer/three/hud/Label.ts
ts/src/renderer/three/hud/ProgressBar.ts

fix: matrixAutoUpdate should not affect too much right now

---

src/gameClasses/components/script/ActionComponent.js
src/gameClasses/components/unit/AbilityComponent.js

particle actions use new script format; ability patch

---

src/gameClasses/ClientNetworkEvents.js
src/gameClasses/Player.js
src/gameClasses/components/ui/MenuUiComponent.js
src/gameClasses/components/ui/PlayerUiComponent.js

gameplay start/stop for cg and poki updates

---

src/gameClasses/ClientNetworkEvents.js

handle cg ad play for survival portal as well

---

ts/engine/components/physics/box2d/distsWrapper/box2dwasmWrapper.ts

fix: spawn sensors automatically

---

ts/src/renderer/three/Renderer.ts

Disable environmental effects like lighting and fog when the editor is not in its play state.

Show/hide enviroment when enter/leave play tab

---

src/gameClasses/ClientNetworkEvents.js

poki commercial break fixes - hide menu and pause music

---

src/gameClasses/ClientNetworkEvents.js

crazy games ad play and then reload

---

src/gameClasses/ClientNetworkEvents.js

cg map travel fixes

---

src/gameClasses/ClientNetworkEvents.js

stop music before map travel in all scenarios

---

src/gameClasses/ClientNetworkEvents.js

cg ad play fixes

---

src/gameClasses/ClientNetworkEvents.js

allows for correct application of data streamed with `streamMode == 3` where only the owning player receives the update.

merge streamData objects so data is not overwritten when received on client

---

ts/src/renderer/three/EntityManager.ts
ts/src/renderer/three/entities/Entity.ts
ts/src/renderer/three/entities/Item.ts
ts/src/renderer/three/entities/Unit.ts
ts/src/renderer/three/hud/FloatingText.ts

fix: revert matrixAutoUpdate as true to prevent the invisible units

---

src/lib/SelectionBox.js
src/lib/SelectionHelper.js
ts/src/renderer/three/Renderer.ts

fix: disable the multiSelection by default until enter the map tab

---

src/gameClasses/Sensor.js
src/gameClasses/components/script/ActionComponent.js
src/gameClasses/components/script/ParameterComponent.js
src/gameClasses/components/unit/AIComponent.js
src/lib/SelectionBox.js
ts/engine/components/physics/box2d/distsWrapper/box2dwasmWrapper.ts
ts/src/renderer/three/Renderer.ts

- auto create sensor if the unit does not have sensor
- getRadius now return the latest one
- cant changeSensorRadius if the unit do not have one
- getRadius return the default value not the latest

fix: sensor

---

engine/components/network/net.io/TaroNetIoServer.js
engine/components/network/net.io/net.io-server/index.js
src/gameClasses/ClientNetworkEvents.js

save data fixes for silent reconnect scenarios

---

engine/components/network/net.io/net.io-server/index.js

set idle user updates

---

src/templates/dev-console.ejs

style: use btn-info for the debugDraw btn

---

ts/engine/components/physics/box2d/distsWrapper/box2dwasmWrapper.ts

fix: if the sensor radius <= 0, then do nothing

---

ts/engine/components/physics/box2d/distsWrapper/box2dwasmWrapper.ts

fix: prevent region sensors rotation

---

ts/src/renderer/three/Renderer.ts

chore: remove the blue rects for multiSelection for now

---

src/gameClasses/ClientNetworkEvents.js
src/gameClasses/Item.js
src/gameClasses/components/script/ActionComponent.js
src/gameClasses/components/script/ParameterComponent.js
ts/src/renderer/three/ParticleSystem.ts
ts/src/renderer/three/Renderer.ts

Created bunch of error handlers that prevented a test game to run locally
https://www.modd.io/play/sT0oFkjQq/

added error handlers for particle emitter stuff

---

src/gameClasses/components/script/ActionComponent.js

secure post requests rate limiting and error reporting fixes

---

ts/src/renderer/three/EntityManager.ts
ts/src/renderer/three/entities/ProjectilePool.ts
ts/src/renderer/three/entities/Unit.ts

fix: scale issue of instancedMesh projectiles

---

ts/src/renderer/three/EntityEditor.ts
ts/src/renderer/three/EntityGizmo.ts
ts/src/renderer/three/EntityManager.ts
ts/src/renderer/three/InitEntity.ts
ts/src/renderer/three/Renderer.ts

fix: undo/redo and duplicate issue in entity tool

---

ts/src/renderer/three/EntityEditor.ts
ts/src/renderer/three/EntityManager.ts
ts/src/renderer/three/Renderer.ts
ts/types/InGameEditor.d.ts

feat: improve undo/redo for regions

---

ts/src/renderer/three/Renderer.ts
ts/src/renderer/three/VoxelEditor.ts
ts/src/renderer/three/VoxelMarker.ts

fix: check tileSize if dontResize is true

---

ts/src/gameClasses/EntitiesToRender.ts
ts/src/renderer/three/Renderer.ts

feat: add frustum culling for updateAllEntities

---

ts/src/renderer/three/entities/ProjectilePool.ts

feat: set instanceMatrix as StreamDrawUsage to improve the fps

---

server/ServerNetworkEvents.js
src/gameClasses/ClientNetworkEvents.js
src/gameClasses/Player.js
src/gameClasses/components/InventoryComponent.js

- cancel trade and return items before initiating player leave
- check whether both players have enough inventory space before finalizing trade

trade fixes

---

src/gameClasses/components/SoundComponent.js

feat: preload the audios when join the game

---

engine/components/network/net.io/TaroNetIoClient.js
engine/components/network/net.io/net.io-client/index.js
src/gameClasses/components/ui/MenuUiComponent.js

disconnect reason fixes based on game status

---

server/ServerNetworkEvents.js
src/gameClasses/ClientNetworkEvents.js
src/gameClasses/components/InventoryComponent.js
src/gameClasses/components/ui/ItemUiComponent.js
src/gameClasses/components/ui/TradeUiComponent.js

Disable Accept button while not enough inventory space avail.

---

ts/src/gameClasses/EntitiesToRender.ts
ts/src/renderer/three/InitEntity.ts
ts/src/renderer/three/Model.ts
ts/src/renderer/three/Renderer.ts
ts/src/renderer/three/entities/Item.ts
ts/src/renderer/three/entities/Unit.ts
ts/types/TaroEntity.d.ts

feat: improve the frustum culling

---

src/gameClasses/Player.js
src/gameClasses/components/script/ActionComponent.js
ts/src/renderer/three/Camera.ts
ts/src/renderer/three/Renderer.ts

action for setting camera yaw
for kart game specifically. Need a camera that rotates yaw according to where player is facing.
[pitchyawroll_2024815_1540.json](https://github.com/user-attachments/files/16627429/pitchyawroll_2024815_1540.json)

set yaw action

---

engine/components/network/net.io/TaroNetIoClient.js
src/gameClasses/components/ui/MenuUiComponent.js

silent reconnect updates from disconnect modal for poki export

---

engine/components/physics/box2d/TaroEntityPhysics.js

fix: region should use the bodyDef.width/height

---

ts/src/renderer/three/Renderer.ts
ts/types/EntityStats.d.ts

fix: add extra checking for items which be held

---

ts/src/renderer/three/Renderer.ts

fix: position forgot to add the initEntityLayer.position.y

---

ts/src/renderer/three/Renderer.ts

fix: do not cull none-init entities

---

ts/src/gameClasses/EntitiesToRender.ts

fix: remove the frustum culling for updateAllEntities for now

---

src/lib/SelectionBox.js

chore: disable multiSelection for now

---

ts/src/renderer/three/EntityEditor.ts
ts/src/renderer/three/EntityGizmo.ts
ts/src/renderer/three/Sprite.ts

fix: remove the selectionHelper for now until fixed the multiSelection

---

ts/src/renderer/three/entities/Item.ts
ts/src/renderer/three/entities/Unit.ts

fix: remove culling for updateMatrix

---

src/gameClasses/Unit.js

fix: the mouse maybe is undefined

---

src/gameClasses/Item.js
src/gameClasses/Projectile.js
src/gameClasses/Unit.js

fix: add guard code to let streamMode = 1 by default

---

engine/components/physics/box2d/TaroEntityPhysics.js

This reverts commit eac85bdbd4dae2a82e81241fcd2453079c78bae0, reversing changes made to 9dce7670b8379ac46c2f415f66e5e95c88055029.

Revert "Merge pull request #1275 from moddio/dimensions-on-init"

---

src/gameClasses/components/script/ActionComponent.js

fix: only send serializable params in runScriptOnClients

---

src/gameClasses/Player.js
src/gameClasses/components/ControlComponent.js
src/gameClasses/components/MobileControlsComponent.js
ts/src/renderer/three/Renderer.ts
ts/types/Client.d.ts

- fix for tap position
- fix secondary tap position

Tap position fix

---

ts/src/renderer/three/Renderer.ts

fix: let gizmo add 'pointdown' eventlistener first

---

src/gameClasses/Item.js

fix: should updateTexture in client

---

src/lib/SelectionHelper.js
ts/src/renderer/three/EntityEditor.ts
ts/src/renderer/three/Renderer.ts

fix: hide selectionHelper whenever leave map tab or choose another tool

---

src/gameClasses/components/script/ActionComponent.js
src/gameClasses/components/script/ParameterComponent.js

object validation updates

---

ts/src/renderer/three/Voxels.ts

fix: layers and preview doesn't show

---

ts/src/renderer/three/InitEntity.ts
ts/src/renderer/three/Voxels.ts

fix: scale

---

ts/src/renderer/phaser/classes/devmode/CommandsController.ts
ts/src/renderer/phaser/classes/devmode/TileEditor.ts
ts/src/renderer/three/Renderer.ts
ts/src/renderer/three/VoxelEditor.ts
ts/src/renderer/three/Voxels.ts

fix: map editor

---

ts/src/renderer/three/Renderer.ts

fix: cant rotate or scale when select only one unit by drag to select

---

ts/src/renderer/three/Camera.ts

feat: set trackingDelay as 0 to move the camera immediately

---

src/gameClasses/components/script/ParameterComponent.js
src/gameClasses/components/unit/AIComponent.js
ts/src/renderer/three/Renderer.ts

- dont use outline shader in play tab
- do not cloneAsset for getItenTypeName action
- add checker in ai component that unit maybe is undefined

feat: improve 10 fps and fix morsels

---

src/gameClasses/components/unit/AStarPathfindingComponent.js

Allow AI to have smarter movement
Walk directly with 145 instead of 12345 in this example
Behavior (img drew by m0dE)
- Red Dot: Old behavior
- Green Line: New behavior
m0dE's request
[game.json](https://github.com/user-attachments/files/16946569/game.json)
https://github.com/user-attachments/assets/cf0d9ea9-908a-434c-8c5a-391844105519

A Star Pathfinding Enhancement (Diagonal)

---

ts/src/renderer/three/AnimatedSprite.ts
ts/src/renderer/three/EntityEditor.ts
ts/src/renderer/three/EntityGizmo.ts
ts/src/renderer/three/InitEntity.ts
ts/src/renderer/three/Sprite.ts
ts/src/renderer/three/Voxels.ts

fix: scale issue for initEntities (animatedSprite)
