src/gameClasses/components/script/ActionComponent.js
The property is actually 'duration' and not 'value'. This change will correct timeout durations.
=> Fix setTimeOut action

engine/components/physics/box2d/TaroEntityPhysics.js
Allows changing physics bounds from the sprite dimensions.
Relates to https://trello.com/c/uY5nmqDS/8566-add-more-fields-in-entity-body-for-fixture-x-y-width-height
=> Add physics bounds override

engine/components/network/net.io/TaroNetIoClient.js, engine/components/physics/box2d/Box2dComponent.js, engine/core/TaroEntity.js, engine/core/TaroObject.js, src/gameClasses/Item.js, src/gameClasses/Projectile.js, src/gameClasses/components/script/ActionComponent.js
- modernize `this._streamMode` to `this._stats.streamMode` due to `this.streamMode` moving entirely within server logic
- fix all conditions that use `streamMode` to decide which stream to update from
- remove 'sourceItem' checks that used to be for determining script-created projectiles but are now defunct
- make sure that projectiles have a `streamMode` setting no matter where they are created from.
This should re-enable server-streamed projectiles.
- setting grenade to `streamMode = 0` rarely has invisible projectile [CSP]
- similar behaviour when `ignoreServerStream = true` [CSP]
These issues appear to be unrelated to this PR.
=> Projectile stream mode

src/gameClasses/components/ui/ScoreboardComponent.js, src/templates/gui.ejs
More Id and class added to scoreboard UI
Some use case on it
- Use #scoreboard-player-rank-0 , 1, 2 to set displaying color to gold, silver, bronze to represent top 3
- Use .scoreboard-player-is-myself to override the green color of self owned player with { color: <some color> !important; }
And more!
Also the pull-right thing in gui.ejs makes local host environment having the leaderboard displayed kinda buggy so it is removed
=> Scoreboard UI id and class

src/gameClasses/components/unit/AIComponent.js
Ordered by footsoldier https://discord.com/channels/303543835345158145/812208366222311434/1119374698283810827
Preview
---
Test
---
Convert the below file to game json to test
[game.txt](https://github.com/moddio/taro2/files/11777193/game.txt)
Press E to TP
Mouse to move around
Both global script and entity script triggers when a* fail and show fading text
=> Added trigger for a* generate failure

engine/components/TaroInputComponent.js
This can avoid mouseDown event received unintentionally when clicking some other div
Solving this: https://trello.com/c/SCEelIw3/8970-clicking-on-editor-elements-often-triggers-item-use
[game.txt](https://github.com/moddio/taro2/files/12216145/game.txt)
It will apply you some velocity when you have mouseUp
Apparently not affecting anything, taro will only execute mouse up abilities if you ever mouseDown
=> Fix unintentional mouse click event

src/gameClasses/Unit.js
removed duplicate call of setOwnerPlayer for a new unit that *this* client owns; nullify taro.client.selectedUnit when it is destroyed; correctly update players unitIds array and selectedUnit when a new one is created
=> client fixes for player owning unit

engine/components/physics/box2d/Box2dComponent.js
- fix the box2dwasm will try to destroy an obj which is not created by new
=> fix: don't destroyObj which is not created by new

src/ClientConfig.js, ts/src/renderer/three/ThreeRenderer.ts, ts/src/renderer/three/ThreeTileset.ts, ts/src/renderer/three/ThreeVoxelMap.ts, ts/src/renderer/three/utils.ts, ts/types/GameComponent.d.ts
Allows 2 tilesets to be set for the voxel map. One for the top/bottom faces of the voxels and the other for the side faces. The UI that hooks up to this feature still has to be implemented.
=> Add multiple tileset support to voxel map

ts/src/renderer/three/ThreeRenderer.ts, ts/src/renderer/three/ThreeSprite.ts
- Turn the flat map layers into voxel layers
- Lower the vertical position of the trees layer and entities
- Fix z-fighting between sprites with the same vertical position
=> Turn flat layers into voxel layers

src/client.js, ts/src/renderer/three/ThreeCamera.ts, ts/src/renderer/three/ThreeRenderer.ts, ts/src/renderer/three/ThreeUnit.ts, ts/types/EntityStats.d.ts, ts/types/GameComponent.d.ts
This PR:
- Sets the camera projection from the editor settings.
- Sets the camera offset from the camera settings of the unit the camera is following.
- Sets the camera pitch range from the camera settings of the unit the camera is following if pointer lock is enabled.
Note: Pointer lock is not yet implemented.
=> Camera config integration

ts/src/renderer/three/ThreeRenderer.ts
This PR fixes a bug where the skybox is rotating with the unit the camera is attached to.
=> Fix skybox rotating with unit

ts/src/renderer/three/ThreeSprite.ts
This PR fixes the issue of billboard sprites only facing the camera when the camera position/rotation updates, it should also happen on creation.
=> Make billboard sprites face camera on creation

src/gameClasses/components/unit/AIComponent.js
- Fix issue that A* AI corrupted when map tile size is force scale to 64x64 whereas its original tile size isn't
- Enhanced A*IsPositionBlocked logic
- Now it checks corners instead of sides
- (i.e. TL, TR, BL, BR instead of T, D, L, R)
- A* will now it take care unit size as well
- Resolved some deadzone and bug related to new A* code that take care unit size
- since it take care unit size
- if a node is too close to wall (i.e. when that node as unit center the unit will collide with a wall) then that node will be invalid
- it will throw A* fail trigger immediately
- this may only affect games with crowd roads but large units (unit size < tileWidth is not supposed to be affected)
https://github.com/moddio/moddio2/assets/62375288/eeceaf58-f27b-4ae9-b517-0e42b50020c4
=> A* Pathfinding Bug Fix and Enhancement

engine/core/TaroBase.js, server/ServerConfig.js, src/ClientConfig.js, src/gameClasses/components/MapComponent.js, src/gameClasses/components/unit/AIComponent.js, src/gameClasses/components/unit/AStarPathfindingComponent.js
- Put A\* logic into another file [AStarPathfindingComponent.js](https://github.com/moddio/moddio2/compare/master...PineappleBrain:AStarImprovement?expand=1#diff-e7fc01e8fbd4a9288377ac2cfcfdd7fef507f60b78a011fd0d424982be63b4db)
- Convert all deep clone into shadow clone
- shadow clone is sufficient `rfdc()(obj)` -> `{...obj}`
- `wallMap` is bool now (no need to check for != 0)
- Added `tileIsWall()` check in [MapComponent.js](https://github.com/moddio/moddio2/compare/master...PineappleBrain:AStarImprovement?expand=1#diff-2891046bb618fc92a22573e2ddff7350f2fe44122b673ef0cef0c61290ada819)
- Added `Math.clamp(val, min, max)` in [TaroBase.js](https://github.com/moddio/moddio2/compare/master...PineappleBrain:AStarImprovement?expand=1#diff-5958cc28f44a6b218b4d3b58d601293b552c0d2c92afc5b4ad3aa9097 …
=> A* Bug Fix and Improvement

ts/src/renderer/three/ThreeRenderer.ts, ts/types/GameComponent.d.ts
Allow a different tileset to be set for the sides of voxels in the 3D renderer.
=> Integrate side tilesets

ts/src/renderer/three/ThreeVoxelMap.ts
This PR fixes the issue of tilemaps sometimes not rendering correctly due to a tile id offset bug.
=> Fix tilemaps sometimes not rendering correctly in the 3D renderer

ts/src/renderer/three/Label.ts, ts/src/renderer/three/Unit.ts
This PR moves the chat bubble closer to the unit to better match the offset used in the Phaser renderer.
=> Fix chat bubble offset in the 3D renderer

engine/components/physics/box2d/Box2dComponent.js, engine/components/physics/box2d/TaroEntityPhysics.js, engine/core/TaroEntity.js, ts/engine/components/physics/box2d/distsWrapper/box2dtsWrapper.ts, ts/engine/components/physics/box2d/distsWrapper/box2dwasmWrapper.ts, ts/engine/components/physics/box2d/distsWrapper/box2dwebWrapper.ts, ts/engine/components/physics/box2d/distsWrapper/planckWrapper.ts
Physics dists internally use a box creation method that creates vertices from position and **half** width/height data. Custom physics bodies (rect only) were sending physics component a body def with width/height instead. The result was physics bodies twice the expected size when using custom dimensions.
These changes affect the local variable names within these dist files and modify the body creation process in `TaroEntityPhysics.js` to send **half** values of width and height to the body creation process.
=> use halfWidth/Height when using dists' box creation method

package.json, server/server.js
On first impression npm run server
EADDRINUSE: address already in use :::80
This change allows the script to take a PORT environment variable.
I also removed a line in startgame() that was doing something similar that but not working. The variable was unused.
The server was almost working straight from git pull apart from these lines;
The port default 80 seem to be blocked on most system. On my linux mint there is no server on port 80 but it will still not allow a server there.
None, I fixed it to make my first build
=> Change standalone server port from 80 to 8080

ts/src/renderer/three/Camera.ts, ts/src/renderer/three/Renderer.ts
This PR adds the ability to pan (left mouse button) and rotate (right mouse button) the camera in while the 'Map' tab is active in the 3D renderer.
=> Add camera pan and rotate functionality in the 3D map editor

ts/src/renderer/phaser/scenes/GameScene.ts, ts/src/renderer/three/Renderer.ts
- phaser renderer do not hide the particles in map tab
- threejs do not hide anything in map tab
- [three.js] 
[threejs_HidePariclesAfterChangedToMap.txt](https://github.com/moddio/moddio2/files/14696607/threejs_HidePariclesAfterChangedToMap.txt)
- [phaser] 
[HidePariclesAfterChangedToMap_2024321_2156.txt](https://github.com/moddio/moddio2/files/14696608/HidePariclesAfterChangedToMap_2024321_2156.txt)
=> fix: hide everything except the map after changed to map tab

engine/core/TaroEntity.js
- after pick some item up or just select it and then dropped it, it won't be on the ground, but is underground sadly
use LAD or any game using threejs renderer
=> fix: dropped bodies which do not have offset will never go back to 0 offset

ts/src/renderer/three/Particles.ts
just using threejs renderer and create particles with transparent png texture
=> feat: discard transparent part of the png texture in particles

engine/core/TaroEntity.js
ensure that loaded variables are streamed to client by using `VariableComponent.update()` instead of directly changing variables object on server
=> ensure that loaded variables are streamed to client

ts/src/gameClasses/DeveloperMode.ts, ts/src/renderer/three/Voxels.ts, ts/types/TaroEngine.d.ts
- support editMapTile
- rejoin game use the latest game map
[EditMapTile.txt](https://github.com/moddio/moddio2/files/14948857/EditMapTile.txt)
(some item effects don't match its description, now, most of them can only edit the 0 layer)
=> feat: support editMapTile and rejoin game use the latest game map

ts/src/renderer/three/Voxels.ts
In order to correspond to the coordinates of threejs, have to add a 0.5 to the x and z
https://www.modd.io/play/RldHVBaxj/
=> fix: forget to add the missing 0.5 to the x and z

src/gameClasses/components/InventoryComponent.js
buying an item with a full inventory except for a stack of items that has exactly enough space to hold the item you are buying will still tell you that your inventory is full (yes I really encountered this and coped so hard I went into f12 and found the bug myself)
bug stupid
=> Fix annoying shop bug

ts/src/renderer/phaser/classes/devmode/CommandsController.ts, ts/src/renderer/three/Renderer.ts, ts/src/renderer/three/VoxelEditor.ts, ts/src/renderer/three/Voxels.ts
=> fix: undo/redo for drag to draw, wrongly order for the mat of the preview top and sides

ts/src/renderer/three/Sprite.ts
To see if this improves the bug that lowers the fps with a compounding effect whenever a unit's body size is changed.
=> 3D: Remove camera onChange callback registration on sprite creation

src/gameClasses/Unit.js, src/gameClasses/components/script/ParameterComponent.js
pick up new items which can be merged wont trigger the unitPicksUpItem event
=> fix: new items which can be merged still need to trigger the unitPicksUpItem

engine/core/TaroEntity.js, src/gameClasses/components/quest/QuestComponent.js
bc we only streamUpdateData after merged, if we didnt merge the quests object, it will only send the latest quests actions object to the clients, not all the action objects.
=> fix: add quests to the auto merged streamUpdateData

src/gameClasses/components/quest/QuestComponent.js
- forgot to streamUpdateData when remove the quest which is active
=> fix: streamUpdateData when removeQuest

ts/src/renderer/three/Renderer.ts
Fixes a crash on a game where data.particleTypes was undefined and Object.values only works on objects.
=> 3D: Add fallbacks/safeguards when Object.values(...) is used

src/gameClasses/components/quest/QuestComponent.js, src/gameClasses/components/script/ActionComponent.js, src/gameClasses/components/script/ParameterComponent.js
quest component may not auto init somehow, just try_init everywhere to keep it safe
=> fix: try_init everywhere

ts/src/gameClasses/DeveloperMode.ts, ts/src/renderer/three/EntityEditor.ts, ts/src/renderer/three/EntityGizmo.ts, ts/src/renderer/three/EntityManager.ts, ts/src/renderer/three/InitEntity.ts, ts/src/renderer/three/Renderer.ts
=> feat: add undo/redo for regions/entities, ctrl+c for copy entities

src/gameClasses/components/MobileControlsComponent.js
Handle adding joysticks in mobile more gracefully. It now supports adding a single joystick which covers the whole screen where previously it covered only half screen
=> Joystick fixes

src/gameClasses/components/unit/AIComponent.js
Previously, AI continued to target units even after they were set to `hidden`. This clears the internal target from the AI unit.
=> remove unit from AIs `targetUnitId` if unit is hidden/disabled

src/gameClasses/components/ControlComponent.js
previously, horizontal movement was possible with the arrow keys--but not WASD--when `movementControlScheme` was set to `none`
=> none value for `movementControlScheme` no longer allows movement

engine/components/network/net.io/net.io-client/index.js, src/ClientConfig.js, src/lib/OBB.js, ts/src/renderer/three/EntityEditor.ts, ts/src/renderer/three/EntityGizmo.ts, ts/src/renderer/three/EntityManager.ts, ts/src/renderer/three/InitEntity.ts, ts/src/renderer/three/Model.ts, ts/src/renderer/three/Renderer.ts, ts/types/OBB.d.ts
- should not select new entity while dragging gizmo
- remove the initEntity after delete it 
- wrong axis is scaled after rotating 3d models (e.g. before rotate, u can scale up the model on the x-axis, it works fine, but if u rotate, the z appear at the position the x used to be, and if u scale up the model on the z-axis, it actually scale up on the x-axis wrongly, bc we use THREE.Box3, the Box3 do not have rotation, use OBB instead)
- the y become 0 somehow after pasted (it's due to the createdEntity was edited twice by the same created action since we would send the action to all the clients include urself, just let itself ignore it)
=> fix: gizmo transformation for 3d

ts/src/renderer/three/Renderer.ts
the new added model may do not have the rotation
=> Revert "fix: rotation should be also blocked when the selectedEntity do not have that rotation field

ts/src/renderer/three/InitEntity.ts
the isBillboard from editor-side seems is a little buggy
e.g.
one model only have one default body, which its isbillBoard is false, but another field( isBillboard ) we use, is true, will edit the editor side as well
=> fix: use entityTypeData.bodies.default.isBillboard to check is billboard or not

src/gameClasses/components/script/ParameterComponent.js
To make client-side scripting easier, this provides a shorter way for client-only scripts to access the local player, which previously had to be done using a `for all players` loop with the `is player (local) client` function.
[localPlayer function test_2024621_147.json](https://github.com/user-attachments/files/15933802/localPlayer.function.test_2024621_147.json)
=> Add localPlayer function

ts/engine/components/physics/box2d/distsWrapper/box2dwasmWrapper.ts, ts/types/GameComponent.d.ts
=> fix: use defaultData.defaultRenderer instead

engine/components/physics/box2d/TaroEntityPhysics.js
In braains, crazy debris round revealed an issue that creates ghost physics bodies on the server when destroy **then** scaleBody are called.
=> fix for ghost bodies when destroy + scale is called

ts/src/renderer/three/Camera.ts, ts/src/renderer/three/Renderer.ts
Fixes the issue were the camera seems to start in an empty place in the world and then takes a while to pan back to the unit its following.
=> Fix following camera overshooting its target

ts/src/renderer/three/Camera.ts, ts/src/renderer/three/EntityEditor.ts, ts/src/renderer/three/EntityGizmo.ts, ts/src/renderer/three/Renderer.ts, ts/src/renderer/three/Utils.ts
=> fix: should not trigger canvas keyEvent whenever focus on other dom

src/gameClasses/components/SoundComponent.js
=> chore: only init audioCtx in client-side

ts/src/renderer/three/Renderer.ts
=> fix: should still emit the pointermove when there is no follow target

src/gameClasses/components/ui/PlayerUiComponent.js
needed for slider interaction (sliders update value on mouse release)
=> add trigger for pointerUp

src/gameClasses/Unit.js
=> fix: should use the width and height after scaled not default one

src/gameClasses/components/script/ActionComponent.js, src/gameClasses/components/script/ParameterComponent.js
now the changeScaleOfEntityBody action does change the size of the physics body, but doesnt update the width and height in it
[🟥Bug Entity Width and Height_202496_144.json](https://github.com/user-attachments/files/16898408/Bug.Entity.Width.and.Height_202496_144.json)
- follow the step in the game hud
=> fix: should update the width and height after scaled
